### ISSUE TITLE
hexo g得到如下错误

### ISSUE THREAD

**Issue by lxy071130** [Fechin/hexo-theme-diaspora#168]
ERROR {
  err: CssSyntaxError: /Users/liuzhen/hexo/themes/diaspora/source/css/diaspora.css:156:44: Unknown word
      at Input.error (/Users/liuzhen/hexo/node_modules/postcss/lib/input.js:128:16)
      at Parser.unknownWord (/Users/liuzhen/hexo/node_modules/postcss/lib/parser.js:561:22)
      at Parser.other (/Users/liuzhen/hexo/node_modules/postcss/lib/parser.js:166:12)
      at Parser.parse (/Users/liuzhen/hexo/node_modules/postcss/lib/parser.js:75:16)
      at parse (/Users/liuzhen/hexo/node_modules/postcss/lib/parse.js:17:12)
      at new LazyResult (/Users/liuzhen/hexo/node_modules/postcss/lib/lazy-result.js:64:16)
      at Processor.<anonymous> (/Users/liuzhen/hexo/node_modules/postcss/lib/processor.js:142:12)
      at Processor.process (/Users/liuzhen/hexo/node_modules/postcss/lib/processor.js:121:23)
      at module.exports (/Users/liuzhen/hexo/node_modules/hexo-autoprefixer/lib/filter.js:19:49)
      at Hexo.tryCatcher (/Users/liuzhen/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/Users/liuzhen/hexo/node_modules/bluebird/js/release/method.js:15:34)
      at /Users/liuzhen/hexo/node_modules/hexo/lib/extend/filter.js:67:52
      at tryCatcher (/Users/liuzhen/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/liuzhen/hexo/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/Users/liuzhen/hexo/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/liuzhen/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/liuzhen/hexo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/liuzhen/hexo/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/liuzhen/hexo/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/liuzhen/hexo/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/liuzhen/hexo/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/liuzhen/hexo/node_modules/bluebird/js/release/async.js:102:5) {
    reason: 'Unknown word',
    file: '/Users/liuzhen/hexo/themes/diaspora/source/css/diaspora.css',
    source: 'body,div,h1,h2,h3,h4,h5,p,ul,li {margin:0;padding:0;font-weight:normal;list-style:none;}\n' +
      'html {-webkit-text-size-adjust:100%;}\n' +
      'html,body {-webkit-tap-highlight-color:rgba(0,0,0,0);-webkit-font-smoothing:antialiased;background:#fff;}\n' +
      "body {font-family:'PingFang SC','Hiragino Sans GB','Microsoft Yahei','WenQuanYi Micro Hei',sans-serif;font-size:14px;position:relative;overflow-x:hidden;}\n" +
      "body:before {background:grey;position:absolute;content:'';display:block;width:14px;height:14px;left:50%;top:50%;margin-left:-7px;margin-top:-7px;border-radius:50%;-webkit-border-radius:50%;-moz-border-radius:50%;-webkit-animation:loading 2s ease-out forwards infinite;-moz-animation:loading 2s ease-out forwards infinite;display:none;}\n" +
      'body.loading:before {display:block;}\n' +
      '@-webkit-keyframes loading {\n' +
      '  0% {-webkit-transform:scale(0.3);}\n' +
      '  50% {-webkit-transform:scale(1.0);}\n' +
      '  100% {-webkit-transform:scale(0.3);}\n' +
      '}\n' +
      '@-moz-keyframes loading {\n' +
      '  0% {-moz-transform:scale(0.3);}\n' +
      '  50% {-moz-transform:scale(1.0);}\n' +
      '  100% {-moz-transform:scale(0.3);}\n' +
      '}\n' +
      'body.loading #container,body.loading #single,body.loading .nav {opacity:0;}\n' +
      'html.loading,body.loading {height:100%;overflow:hidden;}\n' +
      'a,a:hover {text-decoration:none;}\n' +
      'img {display:block;max-width:100%;height:auto;}\n' +
      'audio {display:none;visibility:hidden;opacity:0;width:0;height:0;}\n' +
      '#screen {position:relative;}\n' +
      '#mark {width:100%;height:560px;overflow:hidden;}\n' +
      '.layer {position:relative;}\n' +
      '#cover {position:absolute;max-width:none;}\n' +
      '#header {position:absolute;top:70px;width:100%;}\n' +
      '#header > div {margin:0 60px;position:relative;}\n' +
      '.icon-menu {font-size:20px;padding:6px 6px 5px;border-radius:2px;cursor:pointer;position:absolute;z-index:4;right:0;top:0;margin-top:-3px;background:rgba(255,255,255,.9);}\n' +
      '.icon-search {font-size:20px;padding:6px 6px 5px;border-radius:2px;cursor:pointer;position:absolute;z-index:4;right:40px;top:0;margin-top:-3px;background:rgba(255,255,255,.9);}\n' +
      '.image-logo {z-index:4;position:relative;display:inline-block;-webkit-background-size:75px 32px;-moz-background-size:75px 32px;background-size:75px 32px;background-repeat:no-repeat;background-position:center center;-webkit-mask-box-image:url("/img/logo.png");background-color:white;width:75px;height:32px;mask-image:url("/img/logo.png");mask-size:contain;transition: background-color 0.5s ease-in-out;}\n' +
      'body.mu .image-logo {background-color:black;}\n' +
      '#vibrant {position:absolute;top:0;left:0;width:100%;height:100%;}\n' +
      '#vibrant div {position:absolute;top:0;left:0;width:100%;height:100%;opacity:0;background-color:#000;}\n' +
      '#post0 {width:28%;position:absolute;top:42%;left:10%;}\n' +
      '#post0 p:first-child {color:#fff;font-size:12px;}\n' +
      '#post0 h2 {font-size:28px;margin-top:15px;}\n' +
      '#post0 h2 a {color:#fff;}\n' +
      '#post0 h2 + p {color:#fff;font-size:14px;margin-top:30px;}\n' +
      '.post {margin:100px auto 0;width:1200px;position:relative;}\n' +
      '.post > a {display:inline-block;width:680px;height:440px;overflow:hidden;position:relative;z-index:3;}\n' +
      '.else {position:absolute;background:#fff;text-align:left;top:20px;height:398px;width:498px;border:1px solid #eaeaea;}\n' +
      '.post:nth-child(odd) {text-align:left;}\n' +
      '.post:nth-child(even) {text-align:right;}\n' +
      '.post:nth-child(odd) .else {left:660px;}\n' +
      '.post:nth-child(even) .else {right:660px;}\n' +
      '.else p:first-child {color:#999;font-size:12px;margin:80px 0 0 80px;}\n' +
      '.else h3 {font-size:30px;line-height:1.1;margin:10px 100px 0 80px;}\n' +
      '.else h3 a {color:#333;}\n' +
      '.else h3 + p {color:#555;margin:10px 100px 0 80px;font-size:14px;line-height:1.8;}\n' +
      '.here {position:absolute;left:80px;bottom:80px;color:#999;font-size:13px;}\n' +
      '.here span {display:inline-block;vertical-align:middle;margin-right:10px;font-family:"icomoon","Hiragino Sans GB","Hiragino Sans GB W3","Microsoft YaHei","WenQuanYi Micro Hei",sans-serif;}\n' +
      '.here span:before {display:inline-block;vertical-align:top;margin-right:7px;font-size:16px;}\n' +
      '.here a {display:inline-block;cursor:default;}\n' +
      '#pager {text-align:center;margin:70px 0 0;position:relative;}\n' +
      '#pager a {font-size:14px;letter-spacing:5px;color:#666;border:1px solid #dadada;padding:10px 40px;background:#fff;}\n' +
      '#loader {display:none;position:fixed;top:0;width:100%;height:3px;z-index:100;background-image:-webkit-linear-gradient(left,#F16F5C 0%,#F16F5C 12.5%,#5B56DD 12.5%,#5B56DD 25%,#E15CED 25%,#E15CED 37.5%,#27E559 37.5%,#27E559 50%,#18C8C9 50%,#18C8C9 62.5%,#DC8987 62.5%,#DC8987 75%,#BB83D6 75%,#BB83D6 87.5%,#E774BD 87.5%,#E774BD 100%);background-image:-moz-linear-gradient(left,#F16F5C 0%,#F16F5C 12.5%,#5B56DD 12.5%,#5B56DD 25%,#E15CED 25%,#E15CED 37.5%,#27E559 37.5%,#27E559 50%,#18C8C9 50%,#18C8C9 62.5%,#DC8987 62.5%,#DC8987 75%,#BB83D6 75%,#BB83D6 87.5%,#E774BD 87.5%,#E774BD 100%);}\n' +
      '#top {height:50px;text-align:center;border-bottom:1px solid #f7f7f7;background:#fefefe;width:100%;position:fixed;top:0;z-index:10;display:none;}\n' +
      'body.touch #top {position:relative;}\n' +
      '.icon-icon {color:#333;font-size:20px;position:absolute;left:14px;top:16px;}\n' +
      '.image-icon {-webkit-background-size:24px 24px;-moz-background-size:24px 24px;background-size:24px 24px;background-position:center center;background-repeat:no-repeat;width:24px;height:24px;position:absolute;left:14px;top:15px;color:#333;}\n' +
      '.image-icon:hover {color:black;}\n' +
      '.subtitle {color:#666;font-size:14px;margin-top:16px;display:none;}\n' +
      '.icon-play,.icon-pause,.icon-images {position:absolute;left:70px;color:#666;top:17px;font-size:18px;cursor:pointer;}\n' +
      '.icon-images {left:100px;}\n' +
      '.icon-images.active {color:#EF6D57;}\n' +
      '#top .count {display:none;}\n' +
      '.social {position:absolute;right:0;height:30px;top:12px;}\n' +
      '.share a {display:inline-block;color:#666;margin-right:15px;}\n' +
      '.share a:hover {color:#333;}\n' +
      '.share {position:relative;}\n' +
      '.social > div {display:inline-block;font-size:20px;color:#666;cursor:pointer;margin-left:15px;}\n' +
      '#qr {z-index:10;display:none;position:absolute;background:#fff;padding:16px;border:1px solid #f7f7f7;right:10px;top:50px;}\n' +
      '.bar {position:absolute;height:100%;background:rgba(0,0,0,.07);z-index:-1;width:0;-webkit-transition:width .5s ease;-moz-transition:width .5s ease;transition:width .5s ease;}\n' +
      '.scrollbar {position:absolute;height:2px;width:10px;top:0;background-color:#50bcb6;-webkit-transition:width .5s ease;-moz-transition:width .5s ease;transition:width .5s ease;}\n' +
      'body.touch .scrollbar {display:none;}\n' +
      '.nav {position:fixed;height:100%;width:100%;background:rgba(255,255,255,.97);z-index:3;top:-100%;-webkit-transition:top 0.3s cubic-bezier(0.4,0,0.2,1);-moz-transition:top 0.3s cubic-bezier(0.4,0,0.2,1);transition:top 0.3s cubic-bezier(0.4,0,0.2,1);}\n' +
      'body.mu {overflow:hidden;height:100%;}\n' +
      'html.mu {height:100%;}\n' +
      'body.mu .icon-menu {color:#333;background: none;}\n' +
      'body.mu .icon-search {color:#333;background: none;}\n' +
      'body.mu .icon-menu:before {content:"\\e689";}\n' +
      'body.mu .nav {top:0;}\n' +
      'body.mu .icon-logo {color:#333;}\n' +
      '.menu {text-align:center;margin-top:200px;}\n' +
      '.menu ul {display: -webkit-box;display: -ms-flexbox;display: flex;-webkit-box-pack: center;-ms-flex-pack: center;justify-content: center;-ms-flex-wrap: wrap;flex-wrap: wrap;list-style-type: none;padding: 0;}\n' +
      '.menu li {font-size:18px;display:inline-block;margin:0 2px 2px 0;}\n' +
      '.menu li:not(:last-child) {margin-right: 5px;}\n' +
      '.menu a {display: block;font-size: 20px;color: #666;text-decoration: none;padding: 5px;margin: auto 10px;border-bottom: .1em solid transparent;}\n' +
      '.menu a:hover {color:#333; border-bottom: .1em solid #9e1900; padding-bottom: .15em; transition: 150ms ease-in-out;}\n' +
      '.nav p {color:#999;font-size:12px;position:absolute;width:100%;text-align:center;bottom:30px;}\n' +
      '.nav p a {color:#999;text-decoration:underline;}\n' +
      '.nav p:first-letter {font-family:sans-serif;}\n' +
      '.nav .hitokoto {text-align:center;font-size: 16px;margin: 10% auto 10px;padding: 10px 20px 10px;color: darkgray;max-width:800;}\n' +
      '.nav .footerlinks {font-size: 45px; margin: 20px 1px 30px;padding: 10px 1px 10px;}\n' +
      '.nav .footerlinks a {font-size: 35px; text-decoration:none;}\n' +
      '.nav .footerlinks a:hover { color: #737373;}/* 鼠标移动到链接上 */\n' +
      '\n' +
      '.set {display:block;max-width:768px;margin:0 auto 30px;line-height:2;padding-left:30px}\n' +
      '.set h3 {font-size:22px;font-weight:500;margin:15px 0 20px}\n' +
      '.set a {display:inline-block;position:relative;color:#424242;padding:5px 5px;}\n' +
      '.set a::before {content:"";position:absolute;width:0;right:0;bottom:0;height:2px;background:#2196F3}\n' +
      '.set a:hover {color:#2196F3!important}\n' +
      '.set .category-list-item,.set .tag-list-item {display:inline-block;font-size:17px;text-align:left}\n' +
      '.set .category-list-item .category-list-count,.set .category-list-item .tag-list-count,.set .tag-list-item .category-list-count,.set .tag-list-item .tag-list-count {color:#9E9E9E;font-style:normal}\n' +
      '.set .category-list-item .category-list-count::before,.set .category-list-item .tag-list-count::before,.set .tag-list-item .category-list-count::before,.set .tag-list-item .tag-list-count::before {content:"["}\n' +
      '.set .category-list-item .category-list-count::after,.set .category-list-item .tag-list-count::after,.set .tag-list-item .category-list-count::after,.set .tag-list-item .tag-list-count::after {content:"]"}\n' +
      '.set .category-list-item {width:30%;margin:5px 0}@media screen and (max-width:768px) {.set .category-list-item {width:100%}}\n' +
      '.set .tag-list-item {margin:10px 20px}\n' +
      '.set .search .search-input {width: 100%;height: 42px;background: transparent;border: 0px;border-bottom:2px solid #6558BC;font-size:20px;padding-top: 20px;}\n' +
      '.set .search .search-input[type=text]:focus{outline: none;border: 0px;border-bottom:2px solid #6558BC;}\n' +
      '.set .search .local-search-result {margin-top:30px;}\n' +
      '.set .search .search-result-list {padding:0;margin: 0;}\n' +
      '.set .search .search-result-title {font-size:23px;}\n' +
      '.set .search .search-result {}\n' +
      '.set .search .search-keyword {background:yellow;padding:2px auto 2px;}\n' +
      '.set .search li {list-style: none; margin: 0;border-bottom:1px dashed #E3E3E3;}\n' +
      '.timeline {display:block;max-width:768px;margin:30px auto 40px;padding-left:30px;border-left:3px solid #B0BEC5}\n' +
      '.timeline .timeline-title::before,.timeline .timeline-subtitle::before,.timeline .timeline-item::before {position:absolute;top:50%;transform:translateY(-50'... 16128 more characters,
    line: 156,
    column: 44,
    input: {
      line: 156,
      column: 44,
      source: 'body,div,h1,h2,h3,h4,h5,p,ul,li {margin:0;padding:0;font-weight:normal;list-style:none;}\n' +
        'html {-webkit-text-size-adjust:100%;}\n' +
        'html,body {-webkit-tap-highlight-color:rgba(0,0,0,0);-webkit-font-smoothing:antialiased;background:#fff;}\n' +
        "body {font-family:'PingFang SC','Hiragino Sans GB','Microsoft Yahei','WenQuanYi Micro Hei',sans-serif;font-size:14px;position:relative;overflow-x:hidden;}\n" +
        "body:before {background:grey;position:absolute;content:'';display:block;width:14px;height:14px;left:50%;top:50%;margin-left:-7px;margin-top:-7px;border-radius:50%;-webkit-border-radius:50%;-moz-border-radius:50%;-webkit-animation:loading 2s ease-out forwards infinite;-moz-animation:loading 2s ease-out forwards infinite;display:none;}\n" +
        'body.loading:before {display:block;}\n' +
        '@-webkit-keyframes loading {\n' +
        '  0% {-webkit-transform:scale(0.3);}\n' +
        '  50% {-webkit-transform:scale(1.0);}\n' +
        '  100% {-webkit-transform:scale(0.3);}\n' +
        '}\n' +
        '@-moz-keyframes loading {\n' +
        '  0% {-moz-transform:scale(0.3);}\n' +
        '  50% {-moz-transform:scale(1.0);}\n' +
        '  100% {-moz-transform:scale(0.3);}\n' +
        '}\n' +
        'body.loading #container,body.loading #single,body.loading .nav {opacity:0;}\n' +
        'html.loading,body.loading {height:100%;overflow:hidden;}\n' +
        'a,a:hover {text-decoration:none;}\n' +
        'img {display:block;max-width:100%;height:auto;}\n' +
        'audio {display:none;visibility:hidden;opacity:0;width:0;height:0;}\n' +
        '#screen {position:relative;}\n' +
        '#mark {width:100%;height:560px;overflow:hidden;}\n' +
        '.layer {position:relative;}\n' +
        '#cover {position:absolute;max-width:none;}\n' +
        '#header {position:absolute;top:70px;width:100%;}\n' +
        '#header > div {margin:0 60px;position:relative;}\n' +
        '.icon-menu {font-size:20px;padding:6px 6px 5px;border-radius:2px;cursor:pointer;position:absolute;z-index:4;right:0;top:0;margin-top:-3px;background:rgba(255,255,255,.9);}\n' +
        '.icon-search {font-size:20px;padding:6px 6px 5px;border-radius:2px;cursor:pointer;position:absolute;z-index:4;right:40px;top:0;margin-top:-3px;background:rgba(255,255,255,.9);}\n' +
        '.image-logo {z-index:4;position:relative;display:inline-block;-webkit-background-size:75px 32px;-moz-background-size:75px 32px;background-size:75px 32px;background-repeat:no-repeat;background-position:center center;-webkit-mask-box-image:url("/img/logo.png");background-color:white;width:75px;height:32px;mask-image:url("/img/logo.png");mask-size:contain;transition: background-color 0.5s ease-in-out;}\n' +
        'body.mu .image-logo {background-color:black;}\n' +
        '#vibrant {position:absolute;top:0;left:0;width:100%;height:100%;}\n' +
        '#vibrant div {position:absolute;top:0;left:0;width:100%;height:100%;opacity:0;background-color:#000;}\n' +
        '#post0 {width:28%;position:absolute;top:42%;left:10%;}\n' +
        '#post0 p:first-child {color:#fff;font-size:12px;}\n' +
        '#post0 h2 {font-size:28px;margin-top:15px;}\n' +
        '#post0 h2 a {color:#fff;}\n' +
        '#post0 h2 + p {color:#fff;font-size:14px;margin-top:30px;}\n' +
        '.post {margin:100px auto 0;width:1200px;position:relative;}\n' +
        '.post > a {display:inline-block;width:680px;height:440px;overflow:hidden;position:relative;z-index:3;}\n' +
        '.else {position:absolute;background:#fff;text-align:left;top:20px;height:398px;width:498px;border:1px solid #eaeaea;}\n' +
        '.post:nth-child(odd) {text-align:left;}\n' +
        '.post:nth-child(even) {text-align:right;}\n' +
        '.post:nth-child(odd) .else {left:660px;}\n' +
        '.post:nth-child(even) .else {right:660px;}\n' +
        '.else p:first-child {color:#999;font-size:12px;margin:80px 0 0 80px;}\n' +
        '.else h3 {font-size:30px;line-height:1.1;margin:10px 100px 0 80px;}\n' +
        '.else h3 a {color:#333;}\n' +
        '.else h3 + p {color:#555;margin:10px 100px 0 80px;font-size:14px;line-height:1.8;}\n' +
        '.here {position:absolute;left:80px;bottom:80px;color:#999;font-size:13px;}\n' +
        '.here span {display:inline-block;vertical-align:middle;margin-right:10px;font-family:"icomoon","Hiragino Sans GB","Hiragino Sans GB W3","Microsoft YaHei","WenQuanYi Micro Hei",sans-serif;}\n' +
        '.here span:before {display:inline-block;vertical-align:top;margin-right:7px;font-size:16px;}\n' +
        '.here a {display:inline-block;cursor:default;}\n' +
        '#pager {text-align:center;margin:70px 0 0;position:relative;}\n' +
        '#pager a {font-size:14px;letter-spacing:5px;color:#666;border:1px solid #dadada;padding:10px 40px;background:#fff;}\n' +
        '#loader {display:none;position:fixed;top:0;width:100%;height:3px;z-index:100;background-image:-webkit-linear-gradient(left,#F16F5C 0%,#F16F5C 12.5%,#5B56DD 12.5%,#5B56DD 25%,#E15CED 25%,#E15CED 37.5%,#27E559 37.5%,#27E559 50%,#18C8C9 50%,#18C8C9 62.5%,#DC8987 62.5%,#DC8987 75%,#BB83D6 75%,#BB83D6 87.5%,#E774BD 87.5%,#E774BD 100%);background-image:-moz-linear-gradient(left,#F16F5C 0%,#F16F5C 12.5%,#5B56DD 12.5%,#5B56DD 25%,#E15CED 25%,#E15CED 37.5%,#27E559 37.5%,#27E559 50%,#18C8C9 50%,#18C8C9 62.5%,#DC8987 62.5%,#DC8987 75%,#BB83D6 75%,#BB83D6 87.5%,#E774BD 87.5%,#E774BD 100%);}\n' +
        '#top {height:50px;text-align:center;border-bottom:1px solid #f7f7f7;background:#fefefe;width:100%;position:fixed;top:0;z-index:10;display:none;}\n' +
        'body.touch #top {position:relative;}\n' +
        '.icon-icon {color:#333;font-size:20px;position:absolute;left:14px;top:16px;}\n' +
        '.image-icon {-webkit-background-size:24px 24px;-moz-background-size:24px 24px;background-size:24px 24px;background-position:center center;background-repeat:no-repeat;width:24px;height:24px;position:absolute;left:14px;top:15px;color:#333;}\n' +
        '.image-icon:hover {color:black;}\n' +
        '.subtitle {color:#666;font-size:14px;margin-top:16px;display:none;}\n' +
        '.icon-play,.icon-pause,.icon-images {position:absolute;left:70px;color:#666;top:17px;font-size:18px;cursor:pointer;}\n' +
        '.icon-images {left:100px;}\n' +
        '.icon-images.active {color:#EF6D57;}\n' +
        '#top .count {display:none;}\n' +
        '.social {position:absolute;right:0;height:30px;top:12px;}\n' +
        '.share a {display:inline-block;color:#666;margin-right:15px;}\n' +
        '.share a:hover {color:#333;}\n' +
        '.share {position:relative;}\n' +
        '.social > div {display:inline-block;font-size:20px;color:#666;cursor:pointer;margin-left:15px;}\n' +
        '#qr {z-index:10;display:none;position:absolute;background:#fff;padding:16px;border:1px solid #f7f7f7;right:10px;top:50px;}\n' +
        '.bar {position:absolute;height:100%;background:rgba(0,0,0,.07);z-index:-1;width:0;-webkit-transition:width .5s ease;-moz-transition:width .5s ease;transition:width .5s ease;}\n' +
        '.scrollbar {position:absolute;height:2px;width:10px;top:0;background-color:#50bcb6;-webkit-transition:width .5s ease;-moz-transition:width .5s ease;transition:width .5s ease;}\n' +
        'body.touch .scrollbar {display:none;}\n' +
        '.nav {position:fixed;height:100%;width:100%;background:rgba(255,255,255,.97);z-index:3;top:-100%;-webkit-transition:top 0.3s cubic-bezier(0.4,0,0.2,1);-moz-transition:top 0.3s cubic-bezier(0.4,0,0.2,1);transition:top 0.3s cubic-bezier(0.4,0,0.2,1);}\n' +
        'body.mu {overflow:hidden;height:100%;}\n' +
        'html.mu {height:100%;}\n' +
        'body.mu .icon-menu {color:#333;background: none;}\n' +
        'body.mu .icon-search {color:#333;background: none;}\n' +
        'body.mu .icon-menu:before {content:"\\e689";}\n' +
        'body.mu .nav {top:0;}\n' +
        'body.mu .icon-logo {color:#333;}\n' +
        '.menu {text-align:center;margin-top:200px;}\n' +
        '.menu ul {display: -webkit-box;display: -ms-flexbox;display: flex;-webkit-box-pack: center;-ms-flex-pack: center;justify-content: center;-ms-flex-wrap: wrap;flex-wrap: wrap;list-style-type: none;padding: 0;}\n' +
        '.menu li {font-size:18px;display:inline-block;margin:0 2px 2px 0;}\n' +
        '.menu li:not(:last-child) {margin-right: 5px;}\n' +
        '.menu a {display: block;font-size: 20px;color: #666;text-decoration: none;padding: 5px;margin: auto 10px;border-bottom: .1em solid transparent;}\n' +
        '.menu a:hover {color:#333; border-bottom: .1em solid #9e1900; padding-bottom: .15em; transition: 150ms ease-in-out;}\n' +
        '.nav p {color:#999;font-size:12px;position:absolute;width:100%;text-align:center;bottom:30px;}\n' +
        '.nav p a {color:#999;text-decoration:underline;}\n' +
        '.nav p:first-letter {font-family:sans-serif;}\n' +
        '.nav .hitokoto {text-align:center;font-size: 16px;margin: 10% auto 10px;padding: 10px 20px 10px;color: darkgray;max-width:800;}\n' +
        '.nav .footerlinks {font-size: 45px; margin: 20px 1px 30px;padding: 10px 1px 10px;}\n' +
        '.nav .footerlinks a {font-size: 35px; text-decoration:none;}\n' +
        '.nav .footerlinks a:hover { color: #737373;}/* 鼠标移动到链接上 */\n' +
        '\n' +
        '.set {display:block;max-width:768px;margin:0 auto 30px;line-height:2;padding-left:30px}\n' +
        '.set h3 {font-size:22px;font-weight:500;margin:15px 0 20px}\n' +
        '.set a {display:inline-block;position:relative;color:#424242;padding:5px 5px;}\n' +
        '.set a::before {content:"";position:absolute;width:0;right:0;bottom:0;height:2px;background:#2196F3}\n' +
        '.set a:hover {color:#2196F3!important}\n' +
        '.set .category-list-item,.set .tag-list-item {display:inline-block;font-size:17px;text-align:left}\n' +
        '.set .category-list-item .category-list-count,.set .category-list-item .tag-list-count,.set .tag-list-item .category-list-count,.set .tag-list-item .tag-list-count {color:#9E9E9E;font-style:normal}\n' +
        '.set .category-list-item .category-list-count::before,.set .category-list-item .tag-list-count::before,.set .tag-list-item .category-list-count::before,.set .tag-list-item .tag-list-count::before {content:"["}\n' +
        '.set .category-list-item .category-list-count::after,.set .category-list-item .tag-list-count::after,.set .tag-list-item .category-list-count::after,.set .tag-list-item .tag-list-count::after {content:"]"}\n' +
        '.set .category-list-item {width:30%;margin:5px 0}@media screen and (max-width:768px) {.set .category-list-item {width:100%}}\n' +
        '.set .tag-list-item {margin:10px 20px}\n' +
        '.set .search .search-input {width: 100%;height: 42px;background: transparent;border: 0px;border-bottom:2px solid #6558BC;font-size:20px;padding-top: 20px;}\n' +
        '.set .search .search-input[type=text]:focus{outline: none;border: 0px;border-bottom:2px solid #6558BC;}\n' +
        '.set .search .local-search-result {margin-top:30px;}\n' +
        '.set .search .search-result-list {padding:0;margin: 0;}\n' +
        '.set .search .search-result-title {font-size:23px;}\n' +
        '.set .search .search-result {}\n' +
        '.set .search .search-keyword {background:yellow;padding:2px auto 2px;}\n' +
        '.set .search li {list-style: none; margin: 0;border-bottom:1px dashed #E3E3E3;}\n' +
        '.timeline {display:block;max-width:768px;margin:30px auto 40px;padding-left:30px;border-left:3px solid #B0BEC5}\n' +
        '.timeline .timeline-title::before,.timeline .timeline-subtitle::before,.timeline .timeline-item::before {position:absolute;top:50%;transform:translateY(-50'... 16128 more characters,
      file: '/Users/liuzhen/hexo/themes/diaspora/source/css/diaspora.css'
    }
  }
} Asset render failed: %s css/diaspora.css

**Comment by IvanWei** [comment]
@lxy071130 使用 Node.js 哪一版本？有沒有更多資訊，我是 Node.js v16 可以正常通過 :)
