### ISSUE TITLE
$ hexo g -d ERROR Plugin load failed: hexo-prism-plugin Error

### ISSUE THREAD

**Issue by Brannua** [Fechin/hexo-theme-diaspora#35]
$ hexo g -d
ERROR Plugin load failed: hexo-prism-plugin
Error: `prism_plugin` options should be added to _config.yml file
    at D:\blog\node_modules\hexo-prism-plugin\src\index.js:70:9
    at fs.readFile.then.script (D:\blog\node_modules\hexo\lib\hexo\index.js:240:12)
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\blog\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'field' of undefined
    at Hexo.module.exports (D:\blog\node_modules\hexo-generator-search-zip\lib\zip_generator.js:8:34)
    at Hexo.tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (D:\blog\node_modules\hexo\lib\hexo\index.js:344:26)
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\blog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (D:\blog\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (D:\blog\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (D:\blog\node_modules\bluebird\js\release\map.js:30:10)
    at _drainQueueStep (D:\blog\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by Brannua** [comment]
只是克隆了一下，修改了站点配置的theme名称可以嘛

**Comment by Fechin** [comment]
请检查hexo版本，貌似跟主题无关
